# Some colored makepkg-like functions
#!/bin/bash
# tputcolors

post_upgrade() {
      if [[ $(vercmp 4.2.0 "$2") -eq 1 ]]; then
	  echo -e '\e[1;31m If you are updating pacman from any version prior'
	  echo -e '\e[1;34m ==> pacman 4.2.0'
          echo -e '\e[1;34m Then the pacman database format has changed' 
          echo -e '\e[1;34m Make sure to update the database with:'
          echo -e '\e[1;34m ==> sudo pacman-db-upgrade \e[0m'
      fi
}

