#!/bin/bash
#
# /usr/lib/initscripts/chakra-sysctl
#
# Load sysctl configuration files following
# http://0pointer.de/public/systemd-man/sysctl.d.html
#

shopt -s nullglob

declare -a sysctl_d=(
	/usr/lib/sysctl.d/*.conf
	/etc/sysctl.d/*.conf
	/run/sysctl.d/*.conf
	/etc/sysctl.conf
)
declare -A fragments

# files declared later in the sysctl_d array will override earlier
# Example: `/etc/sysctl.d/foo.conf' supersedes `/usr/lib/sysctl.d/foo.conf'.
for path in "${@:-${sysctl_d[@]}}"; do
	[[ -f $path ]] && fragments[${path##*/}]=$path
done

for path in "${fragments[@]}"; do
	sysctl -q -p "$path"
done

# vim: set ts=2 sw=2 noet:
