#!/bin/bash

KERNEL_NAME=-next
KERNEL_VERSION=5.15.4-1-next

if [ -f /usr/bin/dracut ]; then 

    echo ":: Building initramfs for linux${KERNEL_NAME}-${KERNEL_VERSION}"
	dracut -f --no-hostonly-cmdline "/boot/initramfs-linux${KERNEL_NAME}.img" --kver ${KERNEL_VERSION}

else

    /usr/bin/mkinitcpio -p linux-next

fi
