#!/bin/bash
source PATCHCFG

if [ -d stable-queue ] ;
then
  cd stable-queue
  git pull
  cd ..
else
  git clone git://git.kernel.org/pub/scm/linux/kernel/git/stable/stable-queue.git
fi

if [ -d stable-queue/queue-$_queue ] ;
then
  cd stable-queue/queue-$_queue

  for i in $(cat ./series); 
  do 
     cat $i >> ../../$_patch.patch; 
  done
else
  echo "There is no patch-set this time"
fi